// <auto-generated />
using MakaPrueba.Datos.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MakaPrueba.Datos.Migrations
{
    [DbContext(typeof(MakaContext))]
    partial class MakaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MakaPrueba.Datos.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("PersonTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonTypeId");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 20,
                            Name = "Usuario1",
                            PersonTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Age = 21,
                            Name = "Usuario2",
                            PersonTypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            Age = 22,
                            Name = "Usuario3",
                            PersonTypeId = 1
                        },
                        new
                        {
                            Id = 4,
                            Age = 23,
                            Name = "Usuario4",
                            PersonTypeId = 2
                        });
                });

            modelBuilder.Entity("MakaPrueba.Datos.Entities.PersonType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("PersonTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Teacher"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Students"
                        });
                });

            modelBuilder.Entity("MakaPrueba.Datos.Entities.Person", b =>
                {
                    b.HasOne("MakaPrueba.Datos.Entities.PersonType", "PersonType")
                        .WithMany()
                        .HasForeignKey("PersonTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
